install:
	poetry install

train:
	poetry run python src/models/train.py

predict:
	poetry run python src/models/predict.py

lint:
	poetry run ruff check .

format:
	poetry run ruff format .

precommit:
	poetry run pre-commit install

